### ISSUE TITLE
请问train脚本里面的参数data_root是暮歌的什么数据集？

### ISSUE THREAD

**Issue by HugTibers** [Macielyoung/Chinese-Image-Caption#1]
因为我没有在官网上看到分好的train_muge_caption.csv和valid_muge_caption.csv文件。

**Comment by Macielyoung** [comment]
processor目录下processing脚本的功能，根据官网下载的数据整理组装成训练集和验证集。

**Comment by HugTibers** [comment]
好的 谢谢
